"""sql_107th_question

Revision ID: 4b57f2636a9e
Revises: 03a14ff296f0
Create Date: 2025-12-04 15:42:18.226387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b57f2636a9e'
down_revision: Union[str, None] = '03a14ff296f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index('idx_orders_snum_odate', 'order', ['snum', 'odate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_snum_odate', table_name='order')
    