"""First revision

Revision ID: c4679f6cb5d3
Revises: 
Create Date: 2025-12-02 16:49:55.096054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4679f6cb5d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Londonstaff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Londonstaff',
    sa.Column('snum', sa.INTEGER(), nullable=True),
    sa.Column('sname', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('comm', sa.REAL(), nullable=True)
    )
    # ### end Alembic commands ###
