"""First revision p1

Revision ID: fcb1587cb336
Revises: c4679f6cb5d3
Create Date: 2025-12-02 17:08:10.873624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb1587cb336'
down_revision: Union[str, None] = 'c4679f6cb5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###    
    op.create_table('Londonstaff',
    sa.Column('snum', sa.INTEGER(), nullable=True),
    sa.Column('sname', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('comm', sa.REAL(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Londonstaff')

    # ### end Alembic commands ###
